INSERT INTO Country (id, code, capital, description, nationality, continent)
VALUES (1,  'USA', 'Washington, D.C.', 'Large road network',               'American',      'North America'),
       (2,  'CAN', 'Ottawa',           'Spacious routes, long distances',  'Canadian',      'North America'),
       (3,  'MEX', 'Mexico City',      'Extensive highway system',         'Mexican',       'North America'),
       (4,  'BRA', 'Brasilia',         'Growing logistics infrastructure', 'Brazilian',     'South America'),
       (5,  'ARG', 'Buenos Aires',     'Major transport hubs',             'Argentinian',   'South America'),
       (6,  'GBR', 'London',           'Developed road network',           'British',       'Europe'),
       (7,  'FRA', 'Paris',            'Highway and rail integration',     'French',        'Europe'),
       (8,  'DEU', 'Berlin',           'Efficient autobahn system',        'German',        'Europe'),
       (9,  'CHN', 'Beijing',          'Extensive freight railroads',      'Chinese',       'Asia'),
       (10, 'IND', 'New Delhi',        'Growing road infrastructure',      'Indian',        'Asia'),
       (11, 'JPN', 'Tokyo',            'Advanced logistics technology',    'Japanese',      'Asia'),
       (12, 'RUS', 'Moscow',           'Vast transport networks',          'Russian',       'Europe/Asia'),
       (13, 'AUS', 'Canberra',         'Well-maintained highways',         'Australian',    'Australia/Oceania'),
       (14, 'NZL', 'Wellington',       'Efficient rural transport',        'New Zealander', 'Australia/Oceania'),
       (15, 'ZAF', 'Pretoria',         'Key logistics corridor',           'South African', 'Africa'),
       (16, 'NGA', 'Abuja',            'Emerging road networks',           'Nigerian',      'Africa'),
       (17, 'EGY', 'Cairo',            'Strategic trade routes',           'Egyptian',      'Africa'),
       (18, 'KOR', 'Seoul',            'High-tech fleet management',       'South Korean',  'Asia'),
       (19, 'SAU', 'Riyadh',           'Oil-centric logistics',            'Saudi',         'Asia'),
       (20, 'ESP', 'Madrid',           'Strategic European hub',           'Spanish',       'Europe');